name = "Mechanical Dreams"
author = "ConnorCogged"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "354725a4125f6692c14b9aa915d64eb38d4c6d3da83c869ce4cc868dd3b73876"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
acceptable-game-versions = ["1.21"]
