name = "Mechanical Dreams"
author = "ConnorCogged"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "830d7c70e8bd596f0c16888e32705a89774f5d67229b819e0a7e3ca4a8513243"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
