name = "Mechanical Dreams"
author = "ConnorCogged"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48b92d32458a849a67ce47583f8dcb6d85d8339a40e656c4aa3c3bb8685bf5fb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
acceptable-game-versions = ["1.21"]
